<?php
/**
 * 博客
 *
 * Created by Trick
 * user: Trick
 * Date: 2021/3/26
 * Time: 6:00 下午
 */

namespace App\Controller\Blog;

use PHPZlc\PHPZlc\Bundle\Controller\SystemBaseController;

class BlogController extends SystemBaseController
{
    public function inlet($returnType = SystemBaseController::RETURN_HIDE_RESOURCE, $isLogin = true)
    {
        return parent::inlet($returnType, $isLogin); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->render('blog/index.html.twig');
    }
}